{
 "title": "Rucio Transfer",
 "time": { "from": "now-7d", "to": "now-0m" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "fts",
    "label": "FTS Server",
    "query": "{\"find\": \"terms\", \"field\": \"payload.transfer-endpoint\"}"
   },
   {
    "name": "dst_rse",
    "label": "Dest Site",
    "query": "{\"find\":  \"terms\", \"field\": \"payload.dst-rse\"} "
   },
   {
    "name": "src_rse",
    "label": "Source Site",
    "query": "{\"find\":  \"terms\", \"field\": \"payload.src-rse\"} "
   },
   {
    "name": "group_by",
    "label": "Group By",
    "query": "{\"find\": \"fields\", \"type\": \"keyword\"}"
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": "{\"find\": \"terms\", \"field\": \"payload.protocol\"}"
   },
   { "name": "filters", "label": "Filters" },
   {
    "name": "bin",
    "label": "Bin",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "del_rse",
    "label": "Deletion RSE",
    "query": "{\"find\": \"terms\", \"field\": \"payload.rse\"}"
   }
  ]
 },
 "panels": [
  { "title": "Transfer-done", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Efficiency",
   "type": "timeseries",
   "description": "Number of transfers reported as done from the 1st query, and the number of failed transfers from the second query",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Transfer Throughput",
   "type": "timeseries",
   "description": "Rough data transfer speeds are calculated from the bytes of the files summed over the time bin, divided by the duration (summed over the time bin) reported. \n\nThe binning is locked to 1 hour, as making it adaptive breaks the query.\n\nThe issue is that FTS, the one used here, reports 2 durations as the duration of the FTS event. In contrast, inside the logging there is the duration of only the transfer - This should be negligible for larger files, but may report lower rates for smaller files.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expression": "$A / $B", "type": "math" }
   ]
  },
  {
   "title": "Transfer Successes",
   "type": "timeseries",
   "description": "Count of transfers that are labelled a done, and can be grouped by the Group by variable",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "$group_by",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "created_at",
       "id": "3",
       "settings": { "interval": "$bin", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_type:transfer-done AND payload.dst-rse:${dst_rse:lucene} AND payload.src-rse:${src_rse:lucene} AND payload.protocol:${protocol:lucene} AND payload.transfer-endpoint:${fts:lucene}",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Transfer Failures",
   "type": "timeseries",
   "description": "Count of transfers that are labelled a failed, and can be grouped by the Group by variable",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "$group_by",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      },
      {
       "field": "created_at",
       "id": "3",
       "settings": { "interval": "$bin", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_type:transfer-failed AND payload.dst-rse:${dst_rse:lucene} AND payload.src-rse:${src_rse:lucene} AND payload.protocol:${protocol:lucene} AND payload.transfer-endpoint:${fts:lucene}",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Data moved",
   "type": "timeseries",
   "description": "Sum of the bytes over the binned time, grouped by the group by variable",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "$group_by",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "created_at",
       "id": "3",
       "settings": { "interval": "$bin", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "payload.bytes", "id": "1", "type": "sum" }
     ],
     "query": "event_type:transfer-done AND payload.dst-rse:${dst_rse:lucene} AND payload.src-rse:${src_rse:lucene} AND payload.protocol:${protocol:lucene} AND payload.transfer-endpoint:${fts:lucene}",
     "timeField": "created_at"
    }
   ]
  },
  { "title": "Deletions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Deletions",
   "type": "timeseries",
   "description": "Grouped by payload.rse as this is different for deletions and transfers",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "payload.rse",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "created_at",
       "id": "4",
       "settings": { "interval": "$bin", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_type:deletion-done AND payload.rse:${del_rse:lucene} AND payload.protocol:${protocol:lucene}",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Deletions Rate",
   "type": "timeseries",
   "description": "Grouped by payload.rse as this is different for deletions and transfers",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expression": "$A / $B\n", "type": "math" }
   ]
  },
  { "title": "Transfer Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Transfer Failed Error Reasons",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "payload.reason",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "event_type:transfer-failed",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Transfer Failure information",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "bucketAggs": [
      { "id": "1", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "event_type:transfer-failed AND payload.dst-rse:${dst_rse:lucene} AND payload.src-rse:${src_rse:lucene} AND payload.protocol:${protocol:lucene} AND payload.transfer-endpoint:${fts:lucene}",
     "timeField": "created_at"
    }
   ]
  },
  {
   "title": "Transfer Submission Failure information",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "metrics": [
      {
       "id": "1",
       "settings": {
        "order": "desc",
        "size": "500",
        "useTimeRange": true
       },
       "type": "raw_data"
      }
     ],
     "query": "event_type:transfer-submission_failed",
     "timeField": "created_at"
    }
   ]
  },
  { "title": "Transfer-submitted", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Transfer-submitted by $group_by",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "$group_by",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "created_at",
       "id": "3",
       "settings": { "interval": "$bin", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "field": "payload.bytes", "id": "1", "type": "sum" }
     ],
     "query": "event_type:transfer-done AND payload.dst-rse:${dst_rse:lucene} AND payload.src-rse:${src_rse:lucene} AND payload.protocol:${protocol:lucene} AND payload.transfer-endpoint:${fts:lucene}",
     "timeField": "created_at"
    }
   ]
  }
 ]
}